In [126]:
#https://www.kaggle.com/learn/pandas

import pandas as pd

# DataFrame

1 Key (column), 2 Values (rows, or column labels)

In [127]:
pd.DataFrame(
    {
        'Yes':[50, 21],
        'No':[131, 2]
    }
)

   Yes   No
0   50  131
1   21    2

1 Key (column), 2 Values (rows, or column labels)

In [128]:
pd.DataFrame(
    {
    'Bob': ['I liked it.', 'It was awful.'],
    'Sue': ['Pretty good.', 'Bland.']
    }
)

             Bob           Sue
0    I liked it.  Pretty good.
1  It was awful.        Bland.

Customized index, 1 Key (column), 2 Values (rows, or column labels)

In [129]:
pd.DataFrame(
    {
    'Bob': ['I liked it.', 'It was awful.'],
    'Sue': ['Pretty good.', 'Bland.']
    },
    index=['Product A', 'Product B']
)

                     Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.

# Series

A Series is, in essence, a single column of a DataFrame

In [130]:
pd.Series([1, 2, 3, 4, 5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

Series with customized index and column name (Product A)

In [131]:
pd.Series(
    [30, 35, 40],
    index=['2015 Sales', '2016 Sales', '2017 Sales'],
    name='Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

# Read

Since we are on Google Colab, we will mount the drive first and call the filepath

In [132]:
from google.colab import drive

drive.mount('/content/drive')
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Python for Data Analysis/accompanying_datasets/ex1.csv')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

This CSV has 3 rows (dim=0) and 5 columns (dim=1)

In [133]:
df.shape

(3, 5)

Shows the first 5 rows of the CSV (this CSV only has 3 rows)

In [134]:
df.head()

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

To make pandas use that column for the index (instead of creating a new one from scratch), we can specify an `index_col`

Since we used the 1st column for indexing, the DataFrame shape is now `(3, 4)`

In [135]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Python for Data Analysis/accompanying_datasets/ex1.csv',
                 index_col=0)

print(df.shape)
df.head()

(3, 4)

    b   c   d message
a
1   2   3   4   hello
5   6   7   8   world
9  10  11  12     foo

# Native accessors

With pandas, you can access a DataFrame's columns using attribute access when the column name is a valid Python identifier

In [136]:
df.b

a
1     2
5     6
9    10
Name: b, dtype: int64

You can do the same thing via a Python index call/bracket notation as well

The advantage to the bracket notation is so that you can call columns that may contain special characters (e.g. `'b cd'`)

In [137]:
df['b']

a
1     2
5     6
9    10
Name: b, dtype: int64

# Index-based selection

`.iloc` is the **integer-position-based** way of selecting rows and columns from a DataFrame

In [138]:
df.iloc[0]

b              2
c              3
d              4
message    hello
Name: 1, dtype: object

You may also pass on slicing and lists to an index selection

In [139]:
df.iloc[-5:] # Give me the last 5 rows of the entire DataFrame

    b   c   d message
a
1   2   3   4   hello
5   6   7   8   world
9  10  11  12     foo

In [140]:
df.iloc[:3, 0] # Give me rows 0 through 2 for column 0, same as df.iloc[0:3, 0] or df.iloc[[0, 1, 2], 0]

a
1     2
5     6
9    10
Name: b, dtype: int64

# Label-based selection

`.loc` is a **label-based** way of selecting rows and columns from a DataFrame

Since `.loc` selects per labels, all labels in the slice will be included (e.g. `loc[0:10]` → selects labels 0 through 10, and `loc["flowers":"plants"]` →  selects labels from flowers through plants (position still matters)

In [141]:
df.loc[5]

b              6
c              7
d              8
message    world
Name: 5, dtype: object

# Manipulating the index

You can move any column into an index via `set_index()` (this is a view change)

In [142]:
df.set_index("b")

     c   d message
b
2    3   4   hello
6    7   8   world
10  11  12     foo

# Conditional selection

You can perform boolean operations over the DataFrame for filters

In [143]:
print(df.c.shape)
df.c == 3 # "For each row, is the value in column c equal to 3?

(3,)

a
1     True
5    False
9    False
Name: c, dtype: bool

In [144]:
print(df.loc[df.c == 3].shape)
df.loc[df.c == 3] # Select/filter the rows where column c equals 3

(1, 4)

   b  c  d message
a
1  2  3  4   hello

You can also concatenate selections together as arguments for `.loc`

In [145]:
df.loc[(df.c == 3) & (df.b >= 1)] # Select/filter rows where column c equals 3 AND column b is greater than or equal to 1

   b  c  d message
a
1  2  3  4   hello

`isin` lets you select data whose value "is in" a list of values

In [146]:
df.loc[df.c.isin([1, 3])] # Select/filter rows where column c contains 1 OR 3

   b  c  d message
a
1  2  3  4   hello

`isnull` highlight values which are (or are not) empty (`NaN`)

In [147]:
df.loc[df.c.notnull()] # Select rows where elements are not null (NaN)

    b   c   d message
a
1   2   3   4   hello
5   6   7   8   world
9  10  11  12     foo

# Assigning data

You can assign any element inside a pandas DataFrame with the equal operator, which will be a view (not copy) change

In [148]:
df['c'] = 'wow' # Change all of column c to 'wow'
df

    b    c   d message
a
1   2  wow   4   hello
5   6  wow   8   world
9  10  wow  12     foo

In [149]:
df.loc[5, 'c'] = 'hi' # Change row label 5 at column c to 'hi
df

    b    c   d message
a
1   2  wow   4   hello
5   6   hi   8   world
9  10  wow  12     foo

# Summary functions

`describe()` provides some statistical data of the given object, which only includes integers/floats

In [150]:
df.describe()

          b     d
count   3.0   3.0
mean    6.0   8.0
std     4.0   4.0
min     2.0   4.0
25%     4.0   6.0
50%     6.0   8.0
75%     8.0  10.0
max    10.0  12.0

In order to describe non-statistical (e.g. strings) data, you can add an `include` argument, or you may call the specific strings column

In [151]:
df.describe(include=['object']) # ONLY describe string columns

          c message
count     3       3
unique    2       3
top     wow   hello
freq      2       1

In [152]:
df.describe(include='all') # Describe all columns (integers/floats AND strings)

           b    c     d message
count    3.0    3   3.0       3
unique   NaN    2   NaN       3
top      NaN  wow   NaN   hello
freq     NaN    2   NaN       1
mean     6.0  NaN   8.0     NaN
std      4.0  NaN   4.0     NaN
min      2.0  NaN   4.0     NaN
25%      4.0  NaN   6.0     NaN
50%      6.0  NaN   8.0     NaN
75%      8.0  NaN  10.0     NaN
max     10.0  NaN  12.0     NaN

In [153]:
df.c.describe()

count       3
unique      2
top       wow
freq        2
Name: c, dtype: object

Common features such as `mean()`, `unique()` and `value_counts()` can also be called in pandas

In [154]:
df.b.mean() # Calculate the average of integers/floats in column b

np.float64(6.0)

In [155]:
df.b.unique() # Return unique elements in column b

array([ 2,  6, 10])

In [156]:
df.message.value_counts() # Return counts of elements in column message

message
hello    1
world    1
foo      1
Name: count, dtype: int64

# Maps

`map()` can go through each value and transform it based on the given mapping or function

In [157]:
df_b_mean = df.b.mean()
df.b.map(lambda p:p - df_b_mean) # Take p (element in column b) and return p - df_b_mean

a
1   -4.0
5    0.0
9    4.0
Name: b, dtype: float64

`apply()` is the equivalent method if we want to transform a whole DataFrame by calling a custom method on each row

In [158]:
def remean_b(row):
  row.b = row.b - df_b_mean
  return row

df.apply(remean_b, axis='columns') # Apply remean_b to each row (of column b specified within remean_b), subtracting df_b_mean from column b
                                   # axis='index' applies the function to each column instead of each row (can't do here since row.b specifically means columns)

     b    c   d message
a
1 -4.0  wow   4   hello
5  0.0   hi   8   world
9  4.0  wow  12     foo

`map()` and `apply()` return transformed copies; they do not modify the original DataFrame in place.

pandas allows arithmetic between Series and DataFrames by aligning matching index/column labels

In [159]:
df_b_mean = df.b.mean()
df.b - df_b_mean # Subtract df_b_mean from each value in column b

a
1   -4.0
5    0.0
9    4.0
Name: b, dtype: float64

In [160]:
df.c + '-' + df.message # Concatenate column c and column message via hypen

a
1    wow-hello
5     hi-world
9      wow-foo
dtype: object

# Groupwise analysis

`groupby()` groups rows that have the same value(s) in the specified column(s)

`value_counts()` is just a shortcut to this `groupby()` operation

In [161]:
df.groupby('b').b.count() # Equivalent of df.b.value_counts()

b
2     1
6     1
10    1
Name: b, dtype: int64

In [162]:
df.groupby('message').b.min() # Group the rows by each unique value in message, then find the minimum value of b within each group

message
foo      10
hello     2
world     6
Name: b, dtype: int64

In [163]:
df.groupby('message').apply(lambda df: df.c.iloc[0]) # For each message group, take the first value in column a

/tmp/ipykernel_979/1345282990.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('message').apply(lambda df: df.c.iloc[0]) # For each message group, take the first value in column a

message
foo      wow
hello    wow
world     hi
dtype: object

you can also group by more than one column with a simple list argument

In [164]:
df.groupby(['c', 'message']).apply(lambda df: df.loc[df.b.idxmax()]) # For each unique combination of c and message, return the entire row where column b has its highest value

/tmp/ipykernel_979/3542331572.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby(['c', 'message']).apply(lambda df: df.loc[df.b.idxmax()]) # For each unique combination of c and message, return the entire row where column b has its highest value

              b    c   d message
c   message
hi  world     6   hi   8   world
wow foo      10  wow  12     foo
    hello     2  wow   4   hello

`agg()` can run many different functions on a DataFrame simultaneously

In [165]:
df.groupby(['message']).c.agg([len, min, max]) # Returns the length, maximum value, and minimum value of elements in column c for each unique element in column message

/tmp/ipykernel_979/3376713641.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby(['message']).c.agg([len, min, max]) # Returns the length, maximum value, and minimum value of elements in column c for each unique element in column message
/tmp/ipykernel_979/3376713641.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby(['message']).c.agg([len, min, max]) # Returns the length, maximum value, and minimum value of elements in column c for each unique element in column message

         len  min  max
message
foo        1  wow  wow
hello      1  wow  wow
world      1   hi   hi

# Multi-indexes

A multi-index differs from a regular index in that it has multiple levels, akin to a PivotTable

* Multi-indices have several methods for dealing with their tiered structure which are absent for single-level indices
* They also require two levels of labels to retrieve a value
* Dealing with multi-index output is a common "gotcha" for users new to pandas

In [166]:
messages_df = df.groupby(['message', 'c']).b.agg([len]) # For each unique combination of column message and c, returns the number of values in column b
print(type(messages_df.index))
messages_df

<class 'pandas.core.indexes.multi.MultiIndex'>

             len
message c
foo     wow    1
hello   wow    1
world   hi     1

The most popular multi-index method is for converting back to a regular index, the `reset_index()` method

In [167]:
messages_df.reset_index()

  message    c  len
0     foo  wow    1
1   hello  wow    1
2   world   hi    1

# Sorting

`sort_values()` defaults to an ascending sort, where the lowest values go first

In [168]:
messages_df = messages_df.reset_index()
messages_df.sort_values(by='len') # Sort by column len

  message    c  len
0     foo  wow    1
1   hello  wow    1
2   world   hi    1

However, most of the time we want a descending sort, where the higher numbers go first

In [169]:
messages_df.sort_index(ascending=False) # Sort index in descending order

  message    c  len
2   world   hi    1
1   hello  wow    1
0     foo  wow    1

Better than Excel, you can sort by more than one column at a time

In [170]:
messages_df.sort_values(by=['message', 'c']) # Sort by column message, then by column c

  message    c  len
0     foo  wow    1
1   hello  wow    1
2   world   hi    1

# Dtypes

You can use the `dtype` property to grab the type of a specific column

In [171]:
df.message.dtype # This column contains Python objects (e.g. strings) rather than a specific fixed type like integers or floats

dtype('O')

In [172]:
df.index.dtype # You can also review the index dtype (int64 by default)

dtype('int64')

The `dtypes` property returns the dtype of every column in the DataFrame

In [173]:
df.dtypes

b           int64
c          object
d           int64
message    object
dtype: object

You can convert a column of one type into another, if such a conversion makes sense, by using the `astype()` function

In [174]:
df.b.astype('float64')

a
1     2.0
5     6.0
9    10.0
Name: b, dtype: float64

# Missing data

As an aside, `NaN` (Not a Number) are always `float64` dtype

To select `NaN` entries you can use `pd.isnull()` (or its companion `pd.notnull()`)

In [175]:
df[pd.isnull(df.message)] # Select all elements where column df.message is null, see column view with df.message.isnull()

Empty DataFrame
Columns: [b, c, d, message]
Index: []

You can edit missing values with `fillna()`

In [176]:
df.message.fillna("Unknown") # Fill NaNs with "Unknown"

a
1    hello
5    world
9      foo
Name: message, dtype: object

You can edit any element inside the DataFrame / Series with `replace()`

In [177]:
df.message.replace("hello", "nihao")

a
1    nihao
5    world
9      foo
Name: message, dtype: object

# Renaming index / columns

You can use `rename()` to change index names and/or column names via keyword arguments

In [178]:
df.rename(columns={'message': 'msg'}) # Rename column message to msg

    b    c   d    msg
a
1   2  wow   4  hello
5   6   hi   8  world
9  10  wow  12    foo

Here is an example of index rename via positional calls

In [199]:
df = df.reset_index(drop=True) # drop=True tells pandas not to keep the old index when resetting it, so we effectively got rid of a in here (else we will not have index=0)
df.rename(index={0: 'firstEntry', 1: 'secondEntry'}) # Rename index a to firstEntry, 1 to secondEntry

              b    c   d message
firstEntry    2  wow   4   hello
secondEntry   6   hi   8   world
2            10  wow  12     foo

Both the row index and the column index can have their own name attribute

The complimentary `rename_axis()` method may be used to change these names

In [201]:
df.rename_axis("beta", axis='rows')

       b    c   d message
beta
0      2  wow   4   hello
1      6   hi   8   world
2     10  wow  12     foo

# Combining

The simplest combining method is `concat()`. Given a list of elements, this function will smush those elements together along an axis

This is useful when we have data in different DataFrame or Series objects but having the **same fields (columns)**

In [ ]:
# Example from Kaggle, will not execute since the files are too large for Colab/gdrive

# canadian_youtube = pd.read_csv("../input/youtube-new/CAvideos.csv")
# british_youtube = pd.read_csv("../input/youtube-new/GBvideos.csv")

# pd.concat([canadian_youtube, british_youtube])

The middlemost combiner in terms of complexity is `join()`

`join()` lets you combine different DataFrame objects which have an **index in common**

In [ ]:
# Example from Kaggle, will not execute since the files are too large for Colab/gdrive

# left = canadian_youtube.set_index(['title', 'trending_date'])
# right = british_youtube.set_index(['title', 'trending_date'])

# left.join(right, lsuffix='_CAN', rsuffix='_UK') # suffix matter because the data has the same column names in both British and Canadian datasets

The toughest combining method is `merge()`, which is not covered in this tutorial since most of its functionalities can be done via `join()`

In [179]:

# Both .loc and .iloc can be used for selecting rows AND columns
.iloc
.loc


set_index()
isin
isnull
notnull()
describe()
mean()
unique()
value_counts()
map()
apply()
idxmax()
groupby()
agg()
reset_index()
sort_values()
sort_index()
size()
dtype / dtypes
pd.isnull()
pd.notnull()
fillna()
replace()
rename()
rename_axis()
concat()
join()
merge()

SyntaxError: invalid syntax (2099702023.py, line 2)